# Generated by Django 2.2.7 on 2019-12-15 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('bookingDate', models.DateTimeField()),
                ('showDate', models.DateTimeField()),
                ('status', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Mã')),
                ('name', models.CharField(max_length=50, verbose_name='Tên')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Mã')),
                ('name', models.CharField(max_length=50, verbose_name='Tên')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Mã')),
                ('name', models.CharField(max_length=200, verbose_name='Tên')),
                ('description', models.CharField(blank=True, max_length=500)),
                ('duration', models.IntegerField(verbose_name='Thời lượng (phút)')),
                ('onDate', models.DateField()),
                ('price', models.IntegerField(verbose_name='Giá vé (₫)')),
                ('upcoming', models.BooleanField(verbose_name='Chưa khởi chiếu')),
                ('image', models.ImageField(upload_to='static/images', verbose_name='Ảnh giới thiệu')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Category', verbose_name='Thể loại')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Language', verbose_name='Ngôn ngữ')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Mã')),
                ('numberOfRows', models.IntegerField(verbose_name='Số dãy ghế')),
                ('numberOfCols', models.IntegerField(verbose_name='Số ghế trong một dãy')),
            ],
        ),
        migrations.CreateModel(
            name='MovieShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayOfWeek', models.IntegerField(help_text='Chủ nhật:1, Thứ 2: 2, ..., Thứ 7: 7', verbose_name='Ngày trong tuần')),
                ('time', models.TimeField(help_text='Thời gian dạng HH:mm', verbose_name='Giờ chiếu')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Movie', verbose_name='Phim')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Room', verbose_name='Phòng chiếu')),
            ],
        ),
        migrations.CreateModel(
            name='BookingTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatRow', models.IntegerField()),
                ('seatCol', models.IntegerField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Booking')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Movie'),
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Room'),
        ),
    ]
