# Generated by Django 2.2.5 on 2019-11-23 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Mã')),
                ('name', models.CharField(max_length=50, verbose_name='Tên')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Mã')),
                ('name', models.CharField(max_length=50, verbose_name='Tên')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Mã')),
                ('name', models.CharField(max_length=200, verbose_name='Tên')),
                ('description', models.CharField(blank=True, max_length=500)),
                ('duration', models.IntegerField(verbose_name='Thời lượng (phút)')),
                ('onDate', models.DateField(verbose_name='Ngày khởi chiếu')),
                ('price', models.IntegerField(verbose_name='Giá vé (₫)')),
                ('upcoming', models.BooleanField(verbose_name='Chưa khởi chiếu')),
                ('image', models.ImageField(upload_to='static/images', verbose_name='Ảnh giới thiệu')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Category', verbose_name='Thể loại')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Language', verbose_name='Ngôn ngữ')),
            ],
        ),
        migrations.CreateModel(
            name='MovieShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayOfWeek', models.IntegerField(help_text='Chủ nhật:1, Thứ 2: 2, ..., Thứ 7: 7', verbose_name='Ngày trong tuần')),
                ('time', models.TimeField(help_text='Thời gian dạng HH:mm', verbose_name='Giờ chiếu')),
                ('room', models.CharField(max_length=30, verbose_name='Phòng chiếu')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Movie', verbose_name='Phim')),
            ],
        ),
    ]
