# Generated by Django 2.2.5 on 2019-11-23 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tên')),
                ('country', models.CharField(max_length=30, verbose_name='Quốc gia')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tên')),
                ('country', models.CharField(max_length=30, verbose_name='Quốc gia')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Mã')),
                ('name', models.CharField(max_length=50, verbose_name='Tên')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Mã')),
                ('name', models.CharField(max_length=50, verbose_name='Tên')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Mã')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('description', models.CharField(blank=True, max_length=500)),
                ('releaseYear', models.IntegerField(blank=True, null=True, verbose_name='Năm phát hành')),
                ('file', models.FileField(upload_to='static/music', verbose_name='File nhạc')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Artist', verbose_name='Ca sĩ thể hiện')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Author', verbose_name='Nhạc sĩ sáng tác')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Category', verbose_name='Thể loại')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Language', verbose_name='Ngôn ngữ')),
            ],
        ),
    ]
